apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sonarqube-scan
spec:
  params:
  - name: project-key
    type: string
  - name: project-name
    type: string
  - name: source-dir
    type: string
  - name: sonarqube-url
    type: string
  steps:
  - name: sonarqube-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command:
    - /usr/bin/sonar-scanner
    args:
    - -Dsonar.projectKey=$(params.project-key)
    - -Dsonar.projectName=$(params.project-name)
    - -Dsonar.sources=$(params.source-dir)
    - -Dsonar.host.url=$(params.sonarqube-url)
